version: '3.1'

services:
  weather-spring-api:
    image: vla9isla8/weather-server
    restart: always
    ports:
    - 4000:8080
  weather-client:
    image: vla9isla8/weather-client
    restart: always
    ports:
    - 8888:80
    links:
    - weather-spring-api